markdown            : GFM
# theme               : minima
url: "https://pod.hubbe.net" # the base hostname & protocol for your site

# remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-relative-links

minima:
  skin: dark
